//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagementData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingStatu
    {
        public int booking_id { get; set; }
        public Nullable<bool> food_request { get; set; }
        public Nullable<bool> flower_request { get; set; }
        public Nullable<int> user_id { get; set; }
        public string status { get; set; }
    
        public virtual UsersTable UsersTable { get; set; }
    }
}
