//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagementData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventsTable()
        {
            this.FlowerOrders = new HashSet<FlowerOrder>();
            this.FoodOrders = new HashSet<FoodOrder>();
        }
    
        public int event_id { get; set; }
        public string event_type { get; set; }
        public int guests { get; set; }
        public System.DateTime book_date { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual UsersTable UsersTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlowerOrder> FlowerOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodOrder> FoodOrders { get; set; }
    }
}
