//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagementData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodOrder
    {
        public int food_order_id { get; set; }
        public string food_type { get; set; }
        public string meal_type { get; set; }
        public string dish_type { get; set; }
        public int food_cost { get; set; }
        public Nullable<int> event_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual EventsTable EventsTable { get; set; }
        public virtual UsersTable UsersTable { get; set; }
    }
}
